# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 文章列表
### Send POST request with json body
POST http://localhost:8081/api/articleList
Content-Type: application/json
Access-Token:

{
  "page": 1
}

### 获取单个文章
GET http://localhost:8081/api/article?id=1
Accept: application/json

### 获取文章的所有评论
GET http://localhost:8081/api/comments?article_id=1
Accept: application/json

### 获取文章的所有评论
GET http://localhost:8081/api/prevNext?article_id=1
Accept: application/json

###
POST http://localhost:8081/api/createComment
Content-Type: application/json

{
  "article_id": 1,
  "nickname": "唐JJ",
  "content": "曹晓斌就是个大沙雕！"
}

###

POST http://localhost:8081/api/articles
Content-Type: application/json

{
  "category_id": 3
}

###